### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by JackonLiu** [corochann/chainer-hands-on-tutorial#1]
Traceback (most recent call last):
# Minibatch-size: 64
  File "G:/programmer/python/PycharmProjects/PycharmProjects/cifar100/train_cifar100.py", line 86, in <module>
# epoch: 20
    main()

  File "G:/programmer/python/PycharmProjects/PycharmProjects/cifar100/train_cifar100.py", line 38, in main
    model = archs[args.arch](n_out=class_num)
TypeError: 'module' object is not callable

**Comment by corochann** [comment]
Could you write how did you execute the code?

**Comment by JackonLiu** [comment]
I just run train_cifar100,I can't understand this line
 model = archsargs.arch
could you tell me how this line work,please?

**Comment by corochann** [comment]
https://github.com/corochann/deep-learning-tutorial-with-chainer/blob/master/src/04_cifar_cnn/train_cifar100.py#L42

Do you mean this line? maybe the file is already updated?

```
from CNNSmall import CNNSmall
from CNNMedium import CNNMedium
...
archs = {
    'cnnsmall': CNNSmall,
    'cnnmedium': CNNMedium,
}

model = archs[args.arch](n_out=class_num)
```

It converts the string `args.arch` into specific Chain class `archs[args.arch]`, and instantiate it.

**Comment by JackonLiu** [comment]
could you updated this file?

**Comment by corochann** [comment]
Could you try to download/pull latest source code?

Ref: https://stackoverflow.com/questions/6335681/git-how-do-i-get-the-latest-version-of-my-code
